artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: "https://github.com/kapcodeO/Book-Recommender-System/raw/refs/heads/main/data/book_data.zip"
  dataset_dir: dataset
  ingested_data_dir: ingested_data
  raw_data_dir: raw_data