artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: "https://github.com/kapcodeO/asset-strore/raw/refs/heads/main/book_data.zip"
  dataset_dir: dataset
  ingested_data_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  serialized_data_dir: serialized_objects
  books_csv_file: books.csv
  ratings_csv_file: ratings.csv